travis:
  secure:
    BINSTAR_TOKEN: CukiRAT3/Hkk6j3DoJcfse6a7QYE/CKfJcVvS1HTMpWragwx4XMMxDKko5Tj3dsMMLgPm/MEwZCTxAoghbu+gmCB6SUePvk4xpTg0uuhTvFHJAMT2jbUSWN6VLZ0Z9Nf3fqgmoMV2p9vqORuNy5SRn6Vsdeu57tFcnpBTazJw0PfQvz1QOsLAl+/e3nFgKRoRcjnI6MjFLU7uO1RfiDI392vECQoniUxGzC1SEvbk+FKrBgJOboszB1aK8JJ274lPpt8JabyArggHeMVA2WQj1BdO1sictWY093ehxCRyVgoUzsDpjlOWc22CjB5wsBvlxoBnrbSxETHAdPFfSQjoprK/EG+nMixeDnsXJcdDVBVwWKwYw9I1fVtSf5C9d5Q+HtNViFFQi7305l6WGhJ4Gri809z51963i/5PI1HgkiX0/dHPtKUHMXB7PPWE/6sb35wsRooaHby85i5QwqhsXmpA4l3euocGwO1VZWRPbnes8n48TJbMC/h/U3E0nJ9havmDFu0/4lDUw0HwJYQLCGsqYHSEbR/TQrbdFJObaO/ctC0Q7DQyLRlHG+pvIZowHyd4HDjRoR+lrMSmjrApDzyWYjoWQ4F1fUDp+CcHh+5e0X6QTF84lvjkTEKncUcueHnV/LI3MsI7Lk5f1sXDqTGoEcDvhsNB0SGvOHcCt0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
